on:
  pull_request:
    branches:
      - main
      - dev-v2

name: Synoptic workflow

jobs:
  build_run_workflow:
    runs-on: ubuntu-latest
    name: Build and run workflow
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::quarto
            any::tidyr
            any::readr
            any::lubridate
            any::ggplot2
            any::testthat
      - name: Install other needed packages
        run: |
          pak::pkg_install("COMPASS-DOE/compasstools@v0.2")
        shell: Rscript {0}
      - name: Run data workflow
        run: |
          cd pipeline/
          Rscript --verbose ./driver.R
